changed shebangs to -eu to conform to tests removed removal of old ssh keys modified git_ssh.yaml to use templates to try and alleviate idempotency problems. turn off debug on docker_compose_result unless verbosity of 2 or greated is set. modified parameters to run-ansible to allow ansible-playbook options to be passed to it.

diff --git a/example/run-ansible b/example/run-ansible
--- a/example/run-ansible
+++ b/example/run-ansible
@@ -1,4 +1,4 @@
-#!/usr/bin/env bash
+#!/bin/bash -eu
 #
 # This script is used to run the ansible-galaxy iridl installation.
 # It will check for the existence of the virtual environment: /opt/datalib_venv3.12
@@ -14,54 +14,62 @@ BECOME="--ask-become-pass"
 
 function showhelp()
 {
-  echo "$0 [--build] [--check] [-v]"
-  echo " --check:     Optional argument to check what will be done without making changes."
-  echo " --build:     Optional argument to build or rebuild the maprooms.  This can take a long time."
-  echo " -v:          Optional argument to make the output more verbose.  Use multiple times to increase verbose-ness (i.e. -vv)"
-  echo ""
-  exit
+    echo "$0 [--build] [ansible-playbook arguments]"
+    echo " --build:                   Optional argument to build or rebuild the classic maprooms."
+    echo "                            This can take a long time."
+    echo "ansible-playbook arguments: Optional arguments that will be passed to the ansible-playbook, such as"
+    echo "                            --check and/or -v"
+    echo ""
+    exit
 }
 
+function show_venv_error()
+{
+        echo ""
+        echo "Couldn't activate Python environment ${VENV}"
+        echo "Please review the documentation: https://dldocs.iri.columbia.edu/admin/server/centos9_stream.html#install_python"
+        echo ""
+        exit 1
+
+}
 while (( $# )); do
-  case $1 in
-    --build)
-      BUILD="-e run_update_script=yes"
-      ;;
-    --check)
-      CHECK="--check"
-      ;;
-    --nopw)
-      BECOME="--become"
-      ;;
-    -v*)
-      ;;
-    *)
-      showhelp
-      ;;
-  esac
-  shift
+    case $1 in
+        --build)
+          BUILD="-e run_update_script=yes"
+          shift
+          ;;
+        --nopw)
+          BECOME="--become"
+          shift
+          ;;
+        -h* | --h*)
+          showhelp
+          ;;
+        *)
+          break
+          ;;
+    esac
 done
 
 # Check if the virtual environment exists
 echo -n "checking python virtual environment..."
 if [ -d "${VENV}" ]; then
-  if ! source "${VENV}/bin/activate"; then
-    echo ""
-    echo "Couldn't activate Python environment ${VENV}"
-    echo "Please review the documentation: https://dldocs.iri.columbia.edu/admin/server/centos9_stream.html#install_python"
-    exit 1
-  fi
+    if ! source "${VENV}/bin/activate"; then
+        show_venv_error
+    fi
+else
+    show_venv_error
 fi
 echo "ok"
 
 # check for secrets.yaml file
 if [ ! -f "../secrets.yaml" ]; then
-  echo "../secrets.yaml file doesn't exist.  Please read the documentation on deploy keys and Configuring your Data Library:"
-  echo "* https://dldocs.iri.columbia.edu/admin/git.html#deployment-keys"
-  echo "* https://dldocs.iri.columbia.edu/admin/installation.html#configure-your-data-library-repository"
-  echo ""
-  exit 1
+    echo "../secrets.yaml file doesn't exist.  Please read the documentation on deploy keys and Configuring your Data Library:"
+    echo "* https://dldocs.iri.columbia.edu/admin/git.html#deployment-keys"
+    echo "* https://dldocs.iri.columbia.edu/admin/installation.html#configure-your-data-library-repository"
+    echo ""
+    exit 1
 fi
 
-echo "ansible-playbook ${BECOME} -i inventory.cfg -e @../secrets.yaml ${CHECK} ${BUILD} ${VERBOSE} playbook.yaml"
-ansible-playbook ${BECOME} -i inventory.cfg -e @../secrets.yaml ${CHECK} ${BUILD} ${VERBOSE} playbook.yaml
+echo "ansible-playbook ${BECOME} -i inventory.cfg -e @../secrets.yaml ${BUILD} playbook.yaml $*"
+ansible-playbook ${BECOME} -i inventory.cfg -e @../secrets.yaml ${BUILD} playbook.yaml $*
