fbf update

diff --git a/roles/iridl/templates/update_datalib b/roles/iridl/templates/update_datalib
--- a/roles/iridl/templates/update_datalib
+++ b/roles/iridl/templates/update_datalib
@@ -54,6 +54,10 @@ while [[ $# -gt 0 ]]; do
         build_classic=YES
         shift
         ;;
+    --update-fbf)
+        update_fbf=YES
+        shift
+        ;;
     *)
         fail 1 "Unknown argument '$1'"
         shift
@@ -119,6 +123,15 @@ if [[ -d {{compose_project_dir}} ]]; then  # doesn't exist yet on first run
     docker-compose restart maproom
     # in case one of the services was previously down, tell squid to check again.
     docker-compose exec -T squid squid -k reconfigure
+
+    # update fbf data if fbfmaproom is defined, now that our subnet is running
+    if [ ! -z "${update_fbf}" ]; then
+    {% if fbfmaproom_repo is defined %}
+        docker exec -T fbfmaproom /usr/local/bin/fbf_update_data || fail $? "fbf data update failed"
+    {% else %}
+        echo "The FBF Maproom is not installed on this machine. Ignoring --update-fbf option" >&2
+    {% endif %}
+    fi
 fi
 
 exit 0
