build classic only if necessary and build python maproom

diff --git a/roles/iridl/templates/update_datalib b/roles/iridl/templates/update_datalib
--- a/roles/iridl/templates/update_datalib
+++ b/roles/iridl/templates/update_datalib
@@ -1,16 +1,28 @@
 #!/usr/bin/env bash
 
-export GIT_SSH=/usr/local/bin/ssh-git
-
 fail() {
     echo $2 >&2
     exit $1
 }
 
+while [[ $# -gt 0 ]]; do
+  case $1 in
+    --build-classic)
+	BUILD_CLASSIC=YES
+	shift
+	;;
+    *)
+	fail 1 "Unknown argument '$1'"
+	;;
+  esac
+done
+
 init_git() {
     local repo=$1
     local target=$2
     local version=$3
+    export GIT_SSH=$4
+    local clean=$5
 
     mkdir -p $target
     if [ ! -d $target/.git ]; then
@@ -25,37 +37,47 @@ init_git() {
         fail $? "failed to checkout version $version"
     git submodule update --init --recursive || fail $? "failed to update submodules"
 
+    if [ ! -z "${clean}" ]; then
+	git clean -fdx || fail $? "git clean failed"
+	git submodule foreach --recursive git clean -fdx || fail $? "submodule clean failed"
+    fi
 }
 
 if [[ $(id -u) != 0 ]]; then
     fail 1 "This script should be run with sudo."
 fi
 
+# properly set interactive flags if in an interactive for any docker commands we run
+if [[ -t 1 ]]; then
+    interactive_args=-it
+fi
 
 ### dlentries
 
 if [[ ! -z "{{dlentries_repo}}" ]]; then
-    init_git {{dlentries_repo}} {{dlentries_dir}} {{dlentries_version}}
+    init_git {{dlentries_repo}} {{dlentries_dir}} {{dlentries_version}} /usr/local/bin/ssh-git
 fi
+
+### python maproom
+
+init_git {{python_maproom_repo}} {python_maproom_src_dir}} \
+         {{python_maproom_version}} {{python_maproom_git_ssh}} clean
+
+docker build -t python_maproom:{{python_maproom_version}} .
+
 
 ### maproom
 
-init_git {{maproom_repo}} {{maproom_src_dir}} {{maproom_version}}
+init_git {{maproom_repo}} {{maproom_src_dir}} {{maproom_version}} /usr/local/bin/ssh-git clean
 
-# cleanup beforehand
-git clean -fdx || fail $? "git clean failed"
-git submodule foreach --recursive git clean -fdx || fail $? "submodule clean failed"
+if [ ! -z "${BUILD_CLASSIC}" ]; then
+    docker run --rm $interactive_args --user 0 \
+	   -v $PWD:/build/maproom iridl/maproom-dev:{{maproom_dev_version}} \
+	   ./build.sh utbuild.tag || fail $? "maproom build failed"
 
-if [[ -t 1 ]]; then  # if running in an interactive terminal
-    interactive_args=-it
+    mkdir -p {{maproom_install_dir}} || fail $? "couldn't create install dir"
+    cp -r ___build/* {{maproom_install_dir}} || fail $? "failed to install maprooms"
 fi
-
-docker run --rm $interactive_args --user 0 \
-       -v $PWD:/build/maproom iridl/maproom-dev:{{maproom_dev_version}} \
-       ./build.sh utbuild.tag || fail $? "maproom build failed"
-
-mkdir -p {{maproom_install_dir}} || fail $? "couldn't create install dir"
-cp -r ___build/* {{maproom_install_dir}} || fail $? "failed to install maprooms"
 
 # seemingly necessary to get updates to show up (at least immediately)
 if [[ -d {{compose_project_dir}} ]]; then  # doesn't exist yet on first run
