fixed exec command

diff --git a/roles/iridl/templates/update_datalib b/roles/iridl/templates/update_datalib
--- a/roles/iridl/templates/update_datalib
+++ b/roles/iridl/templates/update_datalib
@@ -127,7 +127,7 @@ if [[ -d {{compose_project_dir}} ]]; then  # doesn't exist yet on first run
     # update fbf data if fbfmaproom is defined, now that our subnet is running
     if [ ! -z "${update_fbf}" ]; then
     {% if fbfmaproom_repo is defined %}
-        docker exec -T fbfmaproom /usr/local/bin/fbf_update_data || fail $? "fbf data update failed"
+        docker-compose exec -T fbfmaproom /usr/local/bin/fbf_update_data || fail $? "fbf data update failed"
     {% else %}
         echo "The FBF Maproom is not installed on this machine. Ignoring --update-fbf option" >&2
     {% endif %}
